enchants:
  ARROW_DAMAGE: false
  ARROW_FIRE: false
  ARROW_INFINITE: false
  ARROW_KNOCKBACK: false
  BINDING_CURSE: false
  CHANNELING: false
  DAMAGE_ALL: false
  DAMAGE_ARTHROPODS: false
  DAMAGE_UNDEAD: false
  DEPTH_STRIDER: false
  DIG_SPEED: false
  DURABILITY: false
  FIRE_ASPECT: false
  FROST_WALKER: false
  IMPALING: false
  KNOCKBACK: false
  LOOT_BONUS_BLOCKS: false
  LOOT_BONUS_MOBS: false
  LOYALTY: false
  LUCK: false
  LURE: false
  MENDING: false
  MULTISHOT: false
  OXYGEN: false
  PIERCING: false
  PROTECTION_ENVIRONMENTAL: false
  PROTECTION_EXPLOSIONS: false
  PROTECTION_FALL: false
  PROTECTION_FIRE: false
  PROTECTION_PROJECTILE: false
  QUICK_CHARGE: false
  RIPTIDE: false
  SILK_TOUCH: false
  SOUL_SPEED: false
  SWEEPING_EDGE: false
  THORNS: false
  VANISHING_CURSE: false
  WATER_WORKER: false